[package]
name = "seed-app"
version = "0.1.0"
authors = ["Alex Kehayias <alex.kehayias@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.3.0"
wasm-bindgen = "0.2.40"
web-sys = "0.3.14"