[package]
name = "woz"
version = "1.1.3"
authors = ["Alex Kehayias <alex.kehayias@gmail.com>"]
edition = "2018"
license = "EPL-1.0"
description = """
Woz is a WebAssembly progressive web app (PWA) toolchain for deploying performant mobile apps distributed for free with a hyperlink.
"""
homepage = "https://woz.sh"
repository = "https://github.com/alexkehayias/woz"
keywords = ["wasm", "webassembly", "woz", "pwa"]
categories = ["wasm", "development-tools"]

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
rusoto_core = "0.36.0"
rusoto_credential = "0.15.0"
rusoto_cognito_identity = "0.36.0"
rusoto_cognito_idp = "0.36.0"
rusoto_cognito_sync = "0.36.0"
rusoto_s3 = "0.36.0"
lazy_static = "1.2.0"
handlebars = "1.1.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
toml = "0.4"
termion = "1.5.1"
failure = "0.1.5"
ring = "0.14.6"
stderrlog = "0.4"