[package]
name = "cli"
version = "0.1.0"
authors = ["Alex Kehayias <alex.kehayias@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
rusoto_core = "0.36.0"
rusoto_cognito_identity = "0.36.0"
rusoto_cognito_idp = "0.36.0"
rusoto_cognito_sync = "0.36.0"