[build.env]
passthrough = [
  "WOZ_WEB_SCHEME",
  "WOZ_WEB_NETLOC",
  "WOZ_IDENTITY_POOL_ID",
  "WOZ_USER_POOL_URL",
  "WOZ_CLIENT_ID",
  "WOZ_S3_BUCKET_NAME",
  "WOZ_ENCRYPTION_PASSWORD",
  "WOZ_ENCRYPTION_SALT",
  "WOZ_PROJECT_ROOT",
  "WOZ_CLI_PROJECT_ROOT",
]