name="Woz Example App"
project_id="seed"
short_name="Woz"
bg_color="black"
lib="wasm-bindgen"
# env="production"
# wasm_path="target/wasm32-unknown-unknown/release/seed_app.wasm"
env="development"
wasm_path="target/wasm32-unknown-unknown/debug/seed_app.wasm"