[package]
name = "foundry"
version = "0.1.0"
authors = ["Alex Kehayias <alex.kehayias@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_core = "0.36.0"
rusoto_s3 = "0.36.0"
chrono = "0.4"
lambda_runtime = "0.2"
serde = "1.0"
serde_derive = "1.0"